//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspen.Data.Model.Contexts
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Aspen.Domain;
    
    public partial class AspenModel : DbContext
    {
        public AspenModel()
            : base("name=AspenModel")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Effect> Effects { get; set; }
        public virtual DbSet<Mood> Moods { get; set; }
        public virtual DbSet<PotionRecipes> PotionRecipes { get; set; }
        public virtual DbSet<Potions> Potions { get; set; }
    }
}
