//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspen.Domain
{
    using System;

    public partial class Potions
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public int ColorID { get; set; }
        public int EffectID { get; set; }
        public int PotionID { get; set; }
        public Nullable<bool> Allergy { get; set; }
    
        public virtual Color navColor { get; set; }
        public virtual Effect navEffect { get; set; }
    }
}
