//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspen.Domain
{
    public partial class PotionRecipes
    {
        public int RecipieID { get; set; }
        public int MoodID { get; set; }
        public int EffectID { get; set; }
        public string PotionRecipieJSON { get; set; }
        public string PotionRecipieIngredientList { get; set; }
    
        public virtual Effect navEffect { get; set; }
        public virtual Mood navMood { get; set; }
    }
}
